### ISSUE TITLE
Analyse project using SonarCloud.io

### ISSUE THREAD

**Issue by tomellm** [github-insights/github-metrics#13]
We can use SonarCloud.io to analyse our source code and detect code smells. SonarCloud will also report about test coverage and the increase/decrease in test coverage when submitting pull-requests.
https://www.sonarsource.com/products/sonarcloud

There is a Gradle plugin to integrate SonarCloud:
https://docs.sonarsource.com/sonarcloud/advanced-setup/ci-based-analysis/sonarscanner-for-gradle

**Comment by tomellm** [comment]
https://sonarcloud.io/organizations/github-insights

**Comment by timpeeters** [comment]
@tomellm typically in our projects, once setup is complete, we only allow CI (GitHub Actions) to publish SonarCloud analysis. We can consider configuring that later on ....

**Comment by tomellm** [comment]
@timpeeters I was about to ask that. So I should deactivate the automatic SonarCloud analysis and let it all happen through Gradle/CI?

**Comment by timpeeters** [comment]
Automatic analysis disabled.
