### ISSUE TITLE
Module naming

### ISSUE THREAD

**Issue by timpeeters** [github-insights/github-metrics#18]
I suppose `webApi` will be used to expose the Prometheus metrics? I would consider renaming this module to something that "screams" it purpose. E.g. `prometheus-exporter`. Indicating it exposes metrics in a Prometheus compatible format.

Otherwise if we were to add a rest api in the future to our application, `webApi` might become somewhat ambigue?

**Comment by tomellm** [comment]
Good point, will do. But on that note, we didn't really know whether to use camelCase or to use dash-case for the names. Since you wrote `prometheus-exporter` dash-case is the one to go for?

Also then reason we decided to go for camelCase was because `buildSrc` directory is in camelCase.

**Comment by tomellm** [comment]
fixed in #24
