### ISSUE TITLE
Consider using Gradle's newer Kotlin DSL instead of Groovy

### ISSUE THREAD

**Issue by timpeeters** [github-insights/github-metrics#19]
We should consider using Kotlin DSL for defining Gradle scripts.
https://docs.gradle.org/current/userguide/migrating_from_groovy_to_kotlin_dsl.html

Not a must, but I would at least like to pitch it.

**Comment by henrybley** [comment]
in pull request #25 we were able to completely migrate to kotlin DSL except for the jacoco aggregate task. as sonar in essence does combine them all anyways is this something we need?
